/**
 * The consumer's copy, against what the producer serves today.
 *
 * `fougere sync` wrote it three weeks ago and the producer moved on. It still compiles —
 * the consumer's types are the old ones and consistent with themselves — so production is
 * where this is found today.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { join } from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { createLocalRunner, type IdentityCard } from '@fougere/core';
import { EMPTY_INVOCATION } from '@fougere/core/contract';
import { testApp, syncedRemotes, heldShapes, syncDriftOf, inSync } from '../src/index.js';

const consumer = join(import.meta.dirname, 'fixtures-synced');

/**
 * The consumer's copy is WRITTEN here, not committed — because it cannot be committed.
 *
 * `fougere sync` records an ABSOLUTE path in `remotes.json` (`SyncHandler`,
 * `updateRemotesRegistry`), so a checked-in copy would name someone else's disk. It was
 * generated by hand once and stayed untracked under `**\/.fougere/`, which made these four
 * tests pass on that machine and fail in every fresh clone — and the CI step that clears
 * the scan cache deleted it locally too.
 *
 * What it writes is exactly what `sync` writes: the entity, and the barrel that re-exports
 * it by name. It is the OLD shape on purpose — `fixtures-drift-old` is the producer that
 * has not moved, `fixtures-drift-new` is the one that has.
 */
beforeAll(async () => {
  const frondDir = join(consumer, '.fougere', 'remotes', 'blog');
  await mkdir(join(frondDir, 'entities'), { recursive: true });
  await writeFile(
    join(frondDir, 'entities', 'Post.ts'),
    "import { entity, primary, text } from '@fougere/schema';\n\n"
    + 'export default class Post extends entity({\n  id: primary(),\n  title: text({ min: 1 }),\n}) {}\n',
  );
  await writeFile(join(frondDir, 'index.ts'), "export { default as Post } from './entities/Post.js';\n");
  await writeFile(
    join(consumer, '.fougere', 'remotes.json'),
    JSON.stringify({ blog: { url: 'http://127.0.0.1:4099', path: frondDir } }, null, 2) + '\n',
  );
});

/** The producer's card, asked the way a consumer asks it. */
const cardOf = async (fixture: string): Promise<IdentityCard> => {
  await using app = await testApp({ root: join(import.meta.dirname, fixture) });
  return await createLocalRunner(app)({ entity: 'rpc', op: 'discover' }, EMPTY_INVOCATION) as IdentityCard;
};

describe('what a consumer synced', () => {
  it('is read from the file `fougere sync` writes', async () => {
    const remotes = await syncedRemotes(consumer);

    expect(remotes.map((one) => one.name)).toEqual(['blog']);
    expect(remotes[0].url).toBe('http://127.0.0.1:4099');
  });

  it('is nothing at all for a project that synced nothing', async () => {
    expect(await syncedRemotes('/tmp/nowhere-at-all')).toEqual([]);
  });

  it('is rebuilt from the classes, since the card itself was not kept', async () => {
    const [blog] = await syncedRemotes(consumer);

    const held = await heldShapes(blog);

    expect([...held.keys()]).toEqual(['Post']);
  });

  it('still matches a producer that has not moved', async () => {
    const [blog] = await syncedRemotes(consumer);
    const drift = syncDriftOf(await heldShapes(blog), await cardOf('fixtures-drift-old'), 'blog');

    expect(inSync(drift), JSON.stringify(drift)).toBe(true);
  });

  it('no longer matches one that has', async () => {
    const [blog] = await syncedRemotes(consumer);
    const drift = syncDriftOf(await heldShapes(blog), await cardOf('fixtures-drift-new'), 'blog');

    expect(inSync(drift)).toBe(false);
    expect(drift.moved.flatMap((one) => one.changes.map((change) => change.kind))).toContain('reshaped');
  });
});
