/**
 * The doors an app serves, as TYPES — what a client needs to narrow `e.code` and nothing else.
 *
 * A third projection of one scan, beside the emitted module and the stated frond. It carries no
 * value: a `.d.ts` costs a consumer nothing at runtime and disappears with the directory it sits
 * in, which is what lets it be rewritten on every boot without anyone having to remember.
 *
 * The runtime scan cannot serve as this. Its operations travel in a `Map`, and a `Map` literal
 * widens its key to `string` — the association between an op and its refusals is exactly what
 * TypeScript drops there. An interface keeps it.
 *
 * Documented: [observability](https://fougere.dev/docs/infra/observability).
 */
import type { ScanResult } from '@fougere/core';

/** A union of string literals, or `never` when the op refuses nothing of its own. */
function codesOf(errors: readonly string[] | undefined): string {
  if (!errors?.length) return 'never';

  return errors.map((code) => `'${code}'`).join(' | ');
}

/**
 * One interface, keyed the way a call is addressed — `post.publish`.
 *
 * A surface is left out: a named surface is a restricted door, and a client holding one is
 * pointed at it rather than choosing per call.
 */
export function emitDoors(scan: ScanResult): string {
  const rows: string[] = [];

  for (const frond of scan.fronds) {
    for (const handler of frond.handlers) {
      if (handler.surface) continue;
      for (const [name, contract] of handler.operations ?? []) {
        rows.push(`  '${handler.address}.${name}': { errors: ${codesOf(contract.errors)} };`);
      }
    }
  }

  return [
    '// Generated by Fougere from what the scan found — do not edit, and do not commit.',
    '// Types only: nothing here reaches a bundle, and it is rewritten whenever the app boots.',
    '',
    '/** Every door this app serves, and what each one can refuse beyond what `kind` implies. */',
    'export interface FougereDoors {',
    ...(rows.length > 0 ? rows.sort() : ['  // This app serves no door.']),
    '}',
    '',
    '/** The refusals one door declares — `never` where it has none of its own. */',
    "export type DoorErrors<Door extends keyof FougereDoors> = FougereDoors[Door]['errors'];",
    '',
  ].join('\n');
}
