/**
 * The doors an app serves, as TYPES — what a client needs to name one and narrow its `e.code`.
 *
 * A third projection of one scan, beside the emitted module and the stated frond. It carries no
 * value: a `.d.ts` costs a consumer nothing at runtime and disappears with the directory it sits
 * in, which is what lets it be rewritten on every boot without anyone having to remember.
 *
 * The runtime scan cannot serve as this. Its operations travel in a `Map`, and a `Map` literal
 * widens its key to `string` — the association between an op and its refusals is exactly what
 * TypeScript drops there. An interface keeps it.
 *
 * Documented: [observability](https://fougere.dev/docs/infra/observability).
 */
import { dirname, relative } from 'node:path';
import { refusalsOf, type ScanResult } from '@fougere/core';
import { servedSurfaces } from '@fougere/core/descriptor';

export interface DoorsOptions {
  /** Where the generated file will sit. Handler imports are written relative to it. */
  outFile: string;
}

/**
 * The specifier a handler is reached by, from where the generated file sits.
 *
 * The type is written WITHOUT `typeof`: that names the CONSTRUCTOR, whose `keyof` is
 * `'prototype'`, and every operation would fail to compile against it.
 */
function specifierOf(filePath: string, outFile: string): string {
  const path = relative(dirname(outFile), filePath).replace(/\.tsx?$/, '.js');

  return path.startsWith('.') ? path : `./${path}`;
}

/**
 * A union of enum MEMBERS — BOTH halves of what a call can come back refusing.
 *
 * `refusalsOf` is core's own table, read here rather than restated: what an op declares is
 * walked from its throw sites, and what the framework adds follows from `kind` and `input`.
 * Writing only the first half would tell a page that an op refuses nothing, when every op can
 * meet a draining door.
 *
 * `ErrorCode` is a string enum, so `'CONFLICT'` is not assignable to it — a literal would read
 * as the right thing and refuse to narrow `FougereError<Code>`, which is the whole point.
 */
function codesOf(contract: { kind?: 'query' | 'command'; input?: unknown; errors?: readonly string[] }): string {
  const codes = refusalsOf(contract);
  if (codes.length === 0) return 'never';

  return codes.map((code) => `ErrorCode.${code}`).join(' | ');
}

/**
 * An augmentation of `FougereDoors`, keyed the way a door is ADDRESSED — `post.publish`, and
 * `public:post.publish` for a named surface.
 *
 * It AUGMENTS rather than declares, so a page reaches the keys through the package it already
 * imports: `useQuery('checkout', 'pay')` narrows against them without naming this file. The
 * interface it fills is empty in `@fougere/core/contract` — the door is addressed the same way
 * on both sides of the wire, and a backend project builds without a front-end package.
 *
 * The prefix is `facadeKeyOf`'s own spelling, because it is the same distinction: a surface is a
 * second door in front of the same handler, serving a subset of its operations. What each op can
 * refuse does not change with the surface — the code that throws is the same — but WHICH ops
 * exist does, and a client pointed at `/_fougere/call/public` must not be offered the rest.
 *
 * A browser reaches the default surface unless it is handed another endpoint, which is why the
 * unprefixed keys are the ones a composable narrows against.
 */
export function emitDoors(scan: ScanResult, options: DoorsOptions): string {
  const rows: string[] = [];
  const handlers = new Map<string, string>();

  for (const frond of scan.fronds) {
    for (const handler of frond.handlers) {
      // NOT `handler.surface`: a surface is also declared in `frond.config.ts`, which names an
      // address without opening a directory for it. `servedSurfaces` is the one reader of both,
      // and it answers `undefined` for the default the way `facadeKeyOf` spells it.
      for (const surface of servedSurfaces(frond, handler)) {
        const at = surface ? `${surface}:${handler.address}` : handler.address;
        handlers.set(at, specifierOf(handler.filePath, options.outFile));
        for (const [name, contract] of handler.operations ?? []) {
          rows.push(`  '${at}.${name}': { errors: ${codesOf(contract)} };`);
        }
      }
    }
  }

  // A named surface shares its handler's class name, so two of them would declare one const.
  // A browser reaches the DEFAULT surface unless it was handed another endpoint, which is the
  // one a page names; the prefixed keys stay in `FougereDoors` for whoever reads them.
  const doors = [...handlers].filter(([at]) => !at.includes(':')).sort();

  return [
    '// Generated by Fougere from what the scan found — do not edit, and do not commit.',
    '// Rewritten whenever the app boots, so it cannot drift from the handlers it was read off.',
    '',
    "import type { ErrorCode, Door } from '@fougere/core/contract';",
    '',
    "declare module '@fougere/core/contract' {",
    '  /** Every door this app serves, and what each one refuses beyond what `kind` implies. */',
    '  interface FougereDoors {',
    ...(rows.length > 0 ? rows.sort().map((row) => `  ${row}`) : ['    // This app serves no door.']),
    '  }',
    '',
    '  /** The class that answers at each address — its operations, and what each one answers. */',
    '  interface FougereHandlers {',
    ...[...handlers].sort().map(([at, from]) => `    '${at}': import('${from}').default;`),
    '  }',
    '}',
    '',
    '// One door per address. A page IMPORTS it, so a project that never generated this file',
    "// fails to resolve rather than falling back to `string` in silence. The value is the",
    '// address and nothing else: the handler is reached as a TYPE, and no server code travels.',
    '//',
    '// Named after the ADDRESS, never after the class: what a page holds is a facade, and calling',
    "// it `PostHandler` would be a value claiming to be a class it is not. A page whose rows are",
    '// already called `post` aliases it on the import, the way any other collision is settled.',
    ...doors.map(([at, from]) =>
      `export const ${at}: FacadeName<import('${from}').default, '${at}'> = { address: '${at}' };`),
    '',
  ].join('\n');
}
