/**
 * The names this project contains, as TYPES — what an operator may write in a config file.
 *
 * A fourth projection of one scan, beside the facade, the emitted module and the stated frond.
 * It exists because `fougere.config.ts` and `frond.config.ts` designate classes, entities and
 * fronds by STRING, and a string is the one thing in this framework that nothing reads back:
 * `ports: { Payment: 'StripePayment' }` survives renaming `StripePayment`, and says so at boot.
 *
 * Ports are written as a RELATION rather than one more union. Two unions would admit
 * `ports: { Payment: 'FileStorage' }` — both names exist, and nothing would say that one does
 * not answer the other.
 *
 * Documented: [ports](https://fougere.dev/docs/business/ports).
 */
import { basesOf, type FrondDescriptor } from '@fougere/core/descriptor';
import { type ScanResult } from '@fougere/core';

export interface NamesOptions {
  /** The keys of `sources:`, which the config states and no scan can find. */
  sources?: readonly string[];
}

/** Sorted, deduplicated, and quoted — the union as it is written. */
function union(names: Iterable<string>): string {
  const all = [...new Set(names)].sort();

  return all.length > 0 ? all.map((name) => `'${name}'`).join(' | ') : 'never';
}

/**
 * The classes a frond declares, whatever convention directory they came from.
 *
 * `basesOf` asks whether a name is answered, which the boot settles against its container. A
 * scan has no container, so what stands in for it is the project itself: a port is a class this
 * scan read. That is the same line drawn from the other side — `RepositoryBase` is returned by a
 * call and declared in no file, so it is excluded here for the reason the boot excludes it.
 */
function declaredIn(frond: FrondDescriptor): Set<string> {
  return new Set([
    ...frond.providers.map((one) => one.ctor.name),
    ...frond.handlers.map((one) => one.ctor.name),
    ...frond.middlewares.map((one) => one.ctor.name),
  ]);
}

export function emitNames(scan: ScanResult, options: NamesOptions = {}): string {
  const fronds = new Set<string>();
  const entities = new Set<string>();
  const handlers = new Set<string>();
  const providers = new Set<string>();
  const middlewares = new Set<string>();
  const ports = new Map<string, Set<string>>();

  for (const frond of scan.fronds) {
    fronds.add(frond.name);
    // BOTH spellings, because the boot admits both: `sources:` lowercases what it is
    // given (`lowerFirst`), so `['Ledger']` and `['ledger']` name one entity. A union of
    // one form would be stricter than what runs, and refuse code that works.
    for (const entity of frond.entities) {
      entities.add(entity.name);
      entities.add(entity.entityClass.name);
    }
    for (const handler of frond.handlers) handlers.add(handler.ctor.name);
    for (const provider of frond.providers) providers.add(provider.ctor.name);
    for (const middleware of frond.middlewares) middlewares.add(middleware.ctor.name);

    const declared = declaredIn(frond);
    for (const [port, answering] of basesOf(frond.providers, (name) => declared.has(name))) {
      const known = ports.get(port) ?? new Set<string>();
      for (const one of answering) known.add(one.ctor.name);
      ports.set(port, known);
    }
  }

  return [
    '// Generated by Fougere from what the scan found — do not edit, and do not commit.',
    '// Rewritten whenever the app boots, so it cannot drift from the project it was read off.',
    '',
    "declare module '@fougere/core' {",
    '  /** Every name this project declares, by kind. A config may write no other. */',
    '  interface FougereNames {',
    `    frond: ${union(fronds)};`,
    `    entity: ${union(entities)};`,
    `    handler: ${union(handlers)};`,
    `    provider: ${union(providers)};`,
    `    middleware: ${union(middlewares)};`,
    `    source: ${union(options.sources ?? [])};`,
    '  }',
    '',
    '  /** Each port, and what extends it — so a config cannot answer one with the other. */',
    '  interface FougerePorts {',
    ...(ports.size > 0
      ? [...ports].sort().map(([port, answering]) => `    ${port}: ${union(answering)};`)
      : ['    // This project declares no port.']),
    '  }',
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
}
