export { entity } from './entity.js';

export * from './vocabulary/index.js';

export { ANONYMOUS_SCHEMA_NAME, Schema } from './Schema.js';
export { type SchemaConstructor } from './SchemaConstructor.js';
export { type SchemaView } from './SchemaView.js';
export { Field } from './field/Field.js';
export { type Fields } from './field/Fields.js';
export { FieldSet } from './field/FieldSet.js';
export { type Shape } from './axis/shape/Shape.js';
export { type ShapeType } from './axis/shape/ShapeType.js';
export { Shapes } from './axis/shape/Shape.js';
export { Role } from './axis/role/Role.js';
export { ON_DELETE, type OnDelete } from './axis/role/Relation.js';
export { type EntityConstructor } from './axis/role/EntityConstructor.js';
export { Lifecycle } from './axis/lifecycle/Lifecycle.js';
export { Boundary } from './axis/boundary/Boundary.js';
export { applyCreate, applyUpdate } from './axis/lifecycle/apply.js';
export { InputRefusal } from './validator/InputRefusal.js';
export { SchemaError } from './SchemaError.js';
export { type ValidationError } from './lib/ValidationError.js';
export { type Verdict } from './lib/Verdict.js';
export { dotted, type ValidationResult } from './lib/ValidationResult.js';

export { Card } from './projection/card/Card.js';
export { Bundle } from './projection/card/Bundle.js';
export { Visibility } from './projection/Visibility.js';
export { Cases } from './projection/Cases.js';
export { type ValidationCase } from './projection/ValidationCase.js';
export type { FieldDescriptor } from './projection/card/FieldDescriptor.js';
export type { SchemaBundle } from './projection/card/SchemaBundle.js';
export type { SchemaDescriptor } from './projection/card/SchemaDescriptor.js';
export type { Change } from './projection/card/Change.js';
export type { Diff } from './projection/card/Diff.js';
export type { SetDiff } from './projection/card/SetDiff.js';
export type { SetDiffOptions } from './projection/card/SetDiffOptions.js';

export * from './lib/index.js';
export { StringFormats } from './axis/shape/StringFormats.js';
export { Generators } from './axis/lifecycle/Generators.js';
export { Boundaries } from './axis/boundary/Decoder.js';
export { type FougereEntityAdapters } from './entity/FougereEntityAdapters.js';
export { type FougereFieldAxes } from './field/FougereFieldAxes.js';
export { InputValidator } from './validator/InputValidator.js';
export { FieldValueValidator } from './validator/FieldValueValidator.js';
export { JsonSchemaValidator } from './validator/JsonSchemaValidator.js';
export type { JsonSchema } from './lib/JsonSchema.js';
export { Axes } from './axis/Axes.js';
export { Format } from './lib/Format.js';
export type { Axis } from './axis/Axis.js';
