// Generated by `fougere load` — edit the weights, the stages and the thresholds.
// Everything else is read from what the app answers: regenerate rather than patch.
import http from 'k6/http';
import { check } from 'k6';

const DOOR = "http://127.0.0.1:4300/_fougere/call";

// Every operation the app serves. A weight of 0 takes one out, visibly.
const OPS = [
  {
    "method": "product.list",
    "weight": 1
  },
  {
    "method": "product.findById",
    "weight": 1
  },
  {
    "method": "product.create",
    "body": {
      "sku": "gDXv8gBIU",
      "name": "MCNJHiFxGrbDH",
      "cents": 750868,
      "status": "draft"
    },
    "weight": 1
  },
  {
    "method": "product.update",
    "body": {
      "sku": "LKJ66",
      "name": "HpiCnX3geczfAAEpYaVsuxZNyUigJfBw2kpP",
      "cents": 496626,
      "status": "listed"
    },
    "weight": 1
  },
  {
    "method": "product.delete",
    "weight": 1
  },
  {
    "method": "product.quote",
    "body": {
      "sku": "gDXv8gBIU",
      "name": "MCNJHiFxGrbDH",
      "cents": 750868,
      "status": "draft"
    },
    "weight": 1
  },
  {
    "method": "order.list",
    "weight": 1
  },
  {
    "method": "order.findById",
    "weight": 1
  },
  {
    "method": "order.create",
    "body": {
      "sku": "GZA",
      "quantity": 68
    },
    "weight": 1
  },
  {
    "method": "order.update",
    "body": {
      "sku": "LKJ66",
      "quantity": 59
    },
    "weight": 1
  },
  {
    "method": "order.delete",
    "weight": 1
  }
];

export const options = {
  // Yours: a flat rate draws flat lines and there is nothing to read in them.
  stages: [
    { duration: '30s', target: 5 },
    { duration: '45s', target: 5 },
    { duration: '30s', target: 0 },
  ],
  // Yours: what counts as too slow is a fact about your users.
  thresholds: { http_req_failed: ['rate<0.01'], http_req_duration: ['p(95)<500'] },
};

const TOTAL = OPS.reduce((sum, op) => sum + op.weight, 0);
let id = 0;

function pick() {
  let roll = Math.random() * TOTAL;
  for (const op of OPS) if ((roll -= op.weight) < 0) return op;
  return OPS[OPS.length - 1];
}

export default function () {
  const op = pick();
  const payload = {"jsonrpc":"2.0"};
  const response = http.post(
    DOOR,
    JSON.stringify({ ...payload, id: ++id, method: op.method, params: { params: {}, query: {}, body: op.body, state: {} } }),
    { headers: { 'content-type': 'application/json' }, tags: { op: op.method } },
  );
  check(response, { 'answered': (r) => r.status === 200 });
}
