import { frameCall } from '@fougere/transport-http';
import { resolveEffectiveOperations } from '@fougere/core';
import type { FrondDescriptor } from '@fougere/core/descriptor';

/**
 * What a load script is read from: the fronds, and nothing else.
 *
 * An `App` satisfies it, and so does a scan — which is what lets `fougere load` answer without
 * booting the project it describes. A boot runs migrations and seeds, so a command that wrote a
 * scenario would also write to the target's database.
 */
interface Serving {
  fronds: readonly FrondDescriptor[];
}
import type { SchemaView } from '@fougere/schema';
import { sampleInput } from './sample.js';

export interface LoadOptions {
  /** Where the calls go. The RPC facade of a running app. */
  facade?: string;
  /** The topology statement, so an op that crosses a process is given the time to. */
  remotes?: Record<string, string>;
  /** Values the generator cannot invent, by entity name — the id a `ref()` points at. */
  given?: Record<string, Record<string, unknown>>;
}

interface Reachable {
  method: string;
  input: unknown;
  /** How many times this op's work crosses a process — what its budget is a function of. */
  hops: number;
}

/** Every operation the app answers, with a body for those that take one. */
export function reachableOps(
  app: Serving,
  given: LoadOptions['given'] = {},
  remotes: Record<string, string> = {},
): Reachable[] {
  const { operations } = resolveEffectiveOperations(app.fronds, { remotes });
  const hops = new Map(operations.map((op) => [`${op.handler.address}.${op.name}`, op.reach.hops]));
  const found: Reachable[] = [];
  for (const frond of app.fronds) {
    for (const handler of frond.handlers) {
      // A named surface is a restricted facade; the load of an app is what its default
      // facade answers, so a surface would count the same operation twice.
      if (handler.surface) continue;
      for (const [op, contract] of handler.operations ?? []) {
        const schema = contract.input as SchemaView | undefined;
        const method = `${handler.address}.${op}`;
        found.push({
          method,
          input: schema ? sampleInput(schema, given[handler.address] ?? {}) : undefined,
          hops: hops.get(method) ?? 0,
        });
      }
    }
  }

  return found;
}

/** A k6 scenario, written from what the app answers. */
export function loadScript(app: Serving, options: LoadOptions = {}): string {
  const facade = options.facade ?? 'http://127.0.0.1:3000/_fougere/call';
  const ops = reachableOps(app, options.given, options.remotes ?? {});
  // The shape, from the one function that states it. `body` is replaced per iteration.
  const envelope = frameCall({ entity: 'ENTITY', op: 'OP' }, { params: {}, query: {}, input: undefined, state: {} } as never, 0);
  // What the envelope carries that an iteration does not fill in itself. Keeping
  // `params` here too put it in the object AND in the spread that overwrites it.
  const perCall = new Set(['method', 'id', 'params']);
  const keys = Object.keys(envelope).filter((key) => !perCall.has(key));

  return `// Generated by \`fougere load\` — edit the weights, the stages and the thresholds.
// Everything else is read from what the app answers: regenerate rather than patch.
import http from 'k6/http';
import { check } from 'k6';

const DOOR = ${JSON.stringify(facade)};

// Every operation the app serves. A weight of 0 takes one out, visibly.
const OPS = ${JSON.stringify(ops.map((op) => ({ ...op, weight: 1 })), null, 2)};

// Yours: how long an op may take here, and what one process boundary is allowed to add. Two
// numbers instead of one, because an op that crosses nothing and an op that crosses twice were
// never the same subject — hops above is read from the code, these two are facts about your
// network.
const BUDGET = { base: 300, perHop: 200 };

export const options = {
  // Yours: a flat rate draws flat lines and there is nothing to read in them.
  stages: [
    { duration: '30s', target: 5 },
    { duration: '45s', target: 5 },
    { duration: '30s', target: 0 },
  ],
  // Yours: the shape of the run.
  // Derived from BUDGET and each op's hops — an op that crosses two processes is not held to
  // the same figure as one that never leaves. k6 reads a threshold per tag, and every call
  // below is tagged with the op it made.
  thresholds: {
    http_req_failed: ['rate<0.01'],
    ...Object.fromEntries(OPS.map((op) => [
      \`http_req_duration{op:\${op.method}}\`,
      [\`p(95)<\${BUDGET.base + op.hops * BUDGET.perHop}\`],
    ])),
  },
};

const TOTAL = OPS.reduce((sum, op) => sum + op.weight, 0);
let id = 0;

function pick() {
  let roll = Math.random() * TOTAL;
  for (const op of OPS) if ((roll -= op.weight) < 0) return op;

  return OPS[OPS.length - 1];
}

export default function () {
  const op = pick();
  const payload = ${JSON.stringify(Object.fromEntries(keys.map((key) => [key, envelope[key as keyof typeof envelope]])))};
  const response = http.post(
    DOOR,
    JSON.stringify({ ...payload, id: ++id, method: op.method, params: { params: {}, query: {}, input: op.input, state: {} } }),
    { headers: { 'content-type': 'application/json' }, tags: { op: op.method } },
  );
  check(response, { 'answered': (r) => r.status === 200 });
}
`;
}
