import { frameCall } from '@fougere/transport-http';
import type { App } from '@fougere/core';
import type { SchemaView } from '@fougere/schema';
import { sampleInput } from './sample.js';

export interface LoadOptions {
  /** Where the calls go. The RPC door of a running app. */
  door?: string;
  /** Values the generator cannot invent, by entity name — the id a `ref()` points at. */
  given?: Record<string, Record<string, unknown>>;
}

interface Reachable {
  method: string;
  body: unknown;
}

/** Every operation the app answers, with a body for those that take one. */
export function reachableOps(app: App, given: LoadOptions['given'] = {}): Reachable[] {
  const found: Reachable[] = [];
  for (const frond of app.fronds) {
    for (const handler of frond.handlers) {
      // A named surface is a restricted door; the load of an app is what its default
      // door answers, so a surface would count the same operation twice.
      if (handler.surface) continue;
      for (const [op, contract] of handler.operations ?? []) {
        const schema = contract.input as SchemaView | undefined;
        found.push({
          method: `${handler.address}.${op}`,
          body: schema ? sampleInput(schema, given[handler.address] ?? {}) : undefined,
        });
      }
    }
  }
  return found;
}

/** A k6 scenario, written from what the app answers. */
export function loadScript(app: App, options: LoadOptions = {}): string {
  const door = options.door ?? 'http://127.0.0.1:3000/_fougere/call';
  const ops = reachableOps(app, options.given);
  // The shape, from the one function that states it. `body` is replaced per iteration.
  const envelope = frameCall({ entity: 'ENTITY', op: 'OP' }, { params: {}, query: {}, body: undefined, state: {} } as never, 0);
  // What the envelope carries that an iteration does not fill in itself. Keeping
  // `params` here too put it in the object AND in the spread that overwrites it.
  const perCall = new Set(['method', 'id', 'params']);
  const keys = Object.keys(envelope).filter((key) => !perCall.has(key));

  return `// Generated by \`fougere load\` — edit the weights, the stages and the thresholds.
// Everything else is read from what the app answers: regenerate rather than patch.
import http from 'k6/http';
import { check } from 'k6';

const DOOR = ${JSON.stringify(door)};

// Every operation the app serves. A weight of 0 takes one out, visibly.
const OPS = ${JSON.stringify(ops.map((op) => ({ ...op, weight: 1 })), null, 2)};

export const options = {
  // Yours: a flat rate draws flat lines and there is nothing to read in them.
  stages: [
    { duration: '30s', target: 5 },
    { duration: '45s', target: 5 },
    { duration: '30s', target: 0 },
  ],
  // Yours: what counts as too slow is a fact about your users.
  thresholds: { http_req_failed: ['rate<0.01'], http_req_duration: ['p(95)<500'] },
};

const TOTAL = OPS.reduce((sum, op) => sum + op.weight, 0);
let id = 0;

function pick() {
  let roll = Math.random() * TOTAL;
  for (const op of OPS) if ((roll -= op.weight) < 0) return op;
  return OPS[OPS.length - 1];
}

export default function () {
  const op = pick();
  const payload = ${JSON.stringify(Object.fromEntries(keys.map((key) => [key, envelope[key as keyof typeof envelope]])))};
  const response = http.post(
    DOOR,
    JSON.stringify({ ...payload, id: ++id, method: op.method, params: { params: {}, query: {}, body: op.body, state: {} } }),
    { headers: { 'content-type': 'application/json' }, tags: { op: op.method } },
  );
  validate(response, { 'answered': (r) => r.status === 200 });
}
`;
}
