/**
 * Shell completion generator — outputs a script for bash/zsh.
 *
 * Sources: scanned frond handlers (commands) + entity fields (flags).
 */
import type { App } from '@fougere/core';
import type { Field } from '@fougere/schema';
import { inputFields } from '@fougere/schema';

function toKebab(name: string): string {
  return name.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase()).replace(/^-/, '');
}

interface CommandMeta {
  name: string;
  flags: string[];
}

function extractCommandMeta(app: App): CommandMeta[] {
  const commands: CommandMeta[] = [];

  for (const frond of app.fronds) {
    const handlerMap = new Map(frond.handlers.map((h) => [h.entityName, h]));

    for (const entity of frond.entities) {
      const handler = handlerMap.get(entity.name);
      if (!handler) continue;

      let facade: Record<string, Function>;
      try { facade = app.resolve(handler.name); } catch { continue; }
      if (typeof facade.execute !== 'function') continue;

      const fields = entity.entityClass.getFields();
      const flags = Object.keys(inputFields(fields))
        .map((key) => `--${toKebab(key)}`);

      commands.push({ name: toKebab(entity.name), flags });
    }
  }

  return commands;
}

export function generateZshCompletion(app: App, binName = 'fougere'): string {
  const commands = extractCommandMeta(app);
  const cmdNames = commands.map((c) => c.name).join(' ');

  const flagCases = commands
    .map((cmd) => {
      const flags = cmd.flags.join(' ');
      return `      ${cmd.name}) flags="${flags}" ;;`;
    })
    .join('\n');

  return `# Auto-generated by @fougere/cli

_${binName}() {
  local -a commands flags
  commands=(${commands.map((c) => `'${c.name}'`).join(' ')})

  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi

  local cmd=\${words[2]}
  case "$cmd" in
${flagCases}
      *) flags="" ;;
  esac

  if [[ "\${words[CURRENT]}" == --* ]]; then
    _values 'flags' \${(s: :)flags}
  fi
}

compdef _${binName} ${binName}
`;
}

export function generateBashCompletion(app: App, binName = 'fougere'): string {
  const commands = extractCommandMeta(app);
  const cmdNames = commands.map((c) => c.name).join(' ');

  const flagCases = commands
    .map((cmd) => {
      const flags = cmd.flags.join(' ');
      return `      ${cmd.name}) COMPREPLY=( $(compgen -W "${flags}" -- "\${cur}") ) ;;`;
    })
    .join('\n');

  return `# Auto-generated by @fougere/cli
_${binName}_completions() {
  local cur prev cmd
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd="\${COMP_WORDS[1]}"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${cmdNames}" -- "\${cur}") )
    return
  fi

  case "$cmd" in
${flagCases}
  esac
}

complete -F _${binName}_completions ${binName}
`;
}
