/** Shell completion generator — outputs a script for bash/zsh. */
import type { App } from '@fougere/core';
import { entityToArgs } from './bridge.js';

function toKebab(name: string): string {
  return name.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase()).replace(/^-/, '');
}

/** What a positional names, said by the field's own name — no table to keep in step. */
const NAMES: Record<string, 'operations' | 'fronds' | undefined> = {
  operation: 'operations',
  frond: 'fronds',
};

interface CommandMeta {
  name: string;
  flags: string[];
  names?: 'operations' | 'fronds';
}

function extractCommandMeta(app: App): CommandMeta[] {
  const commands: CommandMeta[] = [];

  for (const frond of app.fronds) {
    const handlerMap = new Map(frond.handlers.map((h) => [h.address, h]));

    for (const entity of frond.entities) {
      const handler = handlerMap.get(entity.name);
      if (!handler) continue;

      let facade: Record<string, Function>;
      try { facade = app.resolve(handler.name); } catch { continue; }
      if (typeof facade.execute !== 'function') continue;

      // The same function the runner builds citty's args from, so the positional and the
      // flags are the ones the command actually has.
      const args = Object.entries(entityToArgs(entity.entityClass.getFields())) as
        [string, { type?: string }][];
      const positional = args.find(([, def]) => def.type === 'positional')?.[0];

      commands.push({
        name: toKebab(entity.name),
        flags: args.filter(([, def]) => def.type !== 'positional').map(([key]) => `--${key}`),
        ...(positional && NAMES[positional] ? { names: NAMES[positional]! } : {}),
      });
    }
  }

  return commands;
}

export function generateZshCompletion(app: App, binName = 'fougere'): string {
  const commands = extractCommandMeta(app);

  const valueCases = commands
    .filter((cmd) => cmd.names)
    .map((cmd) => `      ${cmd.name}) _${binName}_names ${cmd.names} ;;`)
    .join('\n');

  const flagCases = commands
    .map((cmd) => `      ${cmd.name}) flags="${cmd.flags.join(' ')}" ;;`)
    .join('\n');

  return `# Auto-generated by @fougere/cli

# The project answers; a stale list in this file would not.
_${binName}_names() {
  local -a values
  values=(\${(f)"$(${binName} explain --names $1 2>/dev/null)"})
  (( \${#values} )) && compadd -- \${values}
}

_${binName}() {
  local -a commands flags
  commands=(${commands.map((c) => `'${c.name}'`).join(' ')})

  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi

  local cmd=\${words[2]}

  if [[ "\${words[CURRENT]}" != --* ]]; then
    case "$cmd" in
${valueCases}
    esac
    return
  fi

  case "$cmd" in
${flagCases}
      *) flags="" ;;
  esac
  _values 'flags' \${(s: :)flags}
}

compdef _${binName} ${binName}
`;
}

export function generateBashCompletion(app: App, binName = 'fougere'): string {
  const commands = extractCommandMeta(app);
  const cmdNames = commands.map((c) => c.name).join(' ');

  const valueCases = commands
    .filter((cmd) => cmd.names)
    .map((cmd) => `      ${cmd.name}) names="${cmd.names}" ;;`)
    .join('\n');

  const flagCases = commands
    .map((cmd) => `      ${cmd.name}) COMPREPLY=( $(compgen -W "${cmd.flags.join(' ')}" -- "\${cur}") ) ;;`)
    .join('\n');

  return `# Auto-generated by @fougere/cli
_${binName}_completions() {
  local cur cmd names
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cmd="\${COMP_WORDS[1]}"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${cmdNames}" -- "\${cur}") )
    return
  fi

  if [[ "\${cur}" != --* ]]; then
    names=""
    case "$cmd" in
${valueCases}
    esac
    if [[ -n "\${names}" ]]; then
      # The project answers; a stale list in this file would not.
      COMPREPLY=( $(compgen -W "$(${binName} explain --names "\${names}" 2>/dev/null | tr '\\n' ' ')" -- "\${cur}") )
      return
    fi
  fi

  case "$cmd" in
${flagCases}
  esac
}

complete -F _${binName}_completions ${binName}
`;
}
