/** The scan, written as the STATEMENT an author would have written. */
import { relative } from 'node:path';
import type { FrondDescriptor } from '../descriptor/frond.js';
import type { ScanResult } from './result.js';

type Live = { name?: string };

/**
 * A file becomes the specifier the PROJECT already uses for it: `@fronds/blog/…`, the import scope
 * a handler names its neighbour by, and which the Nuxt module registers as an alias for every
 * frond it found.
 */
function specifierOf(filePath: string, frond: FrondDescriptor): string {
  const inside = relative(frond.source.path, filePath).replace(/\.tsx?$/, '.js');

  return `${frond.source.package}/${inside}`;
}

/** One alias per file, so a class imported twice is one binding and one identity. */
class Imports {
  private readonly byPath = new Map<string, string>();
  private readonly lines: string[] = [];

  default(filePath: string, frond: FrondDescriptor): string {
    const known = this.byPath.get(filePath);
    if (known) return known;
    const alias = `_${this.byPath.size}`;
    this.lines.push(`import ${alias} from '${specifierOf(filePath, frond)}';`);
    this.byPath.set(filePath, alias);

    return alias;
  }

  render(): string {
    return this.lines.join('\n');
  }
}

/** `{ ctor: X, deps: [...] }` when there is something to say, the bare class otherwise. */
function subject(alias: string, deps: string[], extra = ''): string {
  const parts = [
    ...(deps.length ? [`deps: ${JSON.stringify(deps)}`] : []),
    ...(extra ? [extra] : []),
  ];

  return parts.length ? `{ ctor: ${alias}, ${parts.join(', ')} }` : alias;
}

function frondOf(frond: FrondDescriptor, imports: Imports): string {
  const list = (items: string[]): string => `[${items.join(', ')}]`;
  const members: string[] = [];

  if (frond.entities.length) {
    members.push(`entities: ${list(frond.entities.map((e) => imports.default(e.filePath, frond)))}`);
  }
  if (frond.handlers.length) {
    members.push(`handlers: ${list(frond.handlers.map((h) =>
      subject(imports.default(h.filePath, frond), h.deps, h.surface ? `surface: ${JSON.stringify(h.surface)}` : '')))}`);
  }
  if (frond.presenters.length) {
    members.push(`presenters: ${list(frond.presenters.map((p) => subject(imports.default(p.filePath, frond), p.deps)))}`);
  }
  if (frond.collectors.length) {
    members.push(`collectors: ${list(frond.collectors.map((c) => subject(imports.default(c.filePath, frond), c.deps)))}`);
  }
  if (frond.providers.length) {
    members.push(`providers: ${list(frond.providers.map((p) => subject(imports.default(p.filePath, frond), p.deps)))}`);
  }
  // A seed is DATA, not a class — the one member a statement cannot derive from an import.
  if (frond.seeds.length) {
    members.push(`seeds: ${JSON.stringify(frond.seeds.map((s) => ({ entityName: s.entityName, data: s.data })))}`);
  }
  if (frond.surfaces) members.push(`surfaces: ${JSON.stringify(frond.surfaces)}`);

  const scope = (frond.source.package as string | undefined)?.split('/')[0];
  if (scope) members.push(`scope: ${JSON.stringify(scope)}`);

  return `  frond(${JSON.stringify(frond.name)}, {\n    ${members.join(',\n    ')},\n  })`;
}

/** The scan as a list of `frond()` calls — the file an author writes, written for them. */
// Nothing is written relative to the destination, so where the file SITS is not a
// parameter — the alias resolves the same from anywhere.
export function emitStatement(scan: ScanResult): string {
  const imports = new Imports();
  const fronds = scan.fronds.map((f) => frondOf(f as FrondDescriptor & { source: Live }, imports));

  return [
    '// Generated by @fougere/nuxt — what the scan found, as the statement you would write.',
    '//',
    '// Classes are IMPORTED, never restated: `frond()` derives every name from them. Write',
    '// your own `fronds.ts` beside `fougere.config.ts` to state this by hand instead.',
    "import { frond } from '@fougere/core';",
    imports.render(),
    '',
    'export default [',
    `${fronds.join(',\n')},`,
    '];',
    '',
  ].join('\n');
}
