/**
 * The command the generated header has been naming all along.
 *
 * `loadScript` was exported and tested, its one caller was a script by hand in a demo, and the
 * file it writes says `Generated by \`fougere load\`` — a command that did not exist.
 */
import { describe, expect, it } from 'vitest';
import { join } from 'node:path';
import LoadHandler from '../fronds/analysis/handlers/LoadHandler.js';
import ProjectScan from '../fronds/analysis/services/ProjectScan.js';

const fixture = join(import.meta.dirname, 'fixtures-graph');
/** `out: ''` keeps it in memory — a test that describes a project may not write into it. */
const load = (input: Record<string, unknown> = {}) =>
  new LoadHandler(new ProjectScan()).execute({ root: fixture, out: '', ...input });

describe('load', () => {
  it('puts every operation the default door answers under load', async () => {
    const scenario = await load();

    expect(scenario.operations).toEqual(['commande.servable', 'article.onHand']);
    expect(scenario.file).toBeNull();
  }, 30_000);

  /** Read from the SCAN: a boot runs migrations and plants seeds, which describing must not. */
  it('answers without booting the project it describes', async () => {
    const scenario = await load({ door: 'http://127.0.0.1:4200/_fougere/call' });

    expect(scenario.door).toBe('http://127.0.0.1:4200/_fougere/call');
    expect(scenario.script).toContain('http://127.0.0.1:4200/_fougere/call');
  }, 30_000);

  /** What it derives, and what it marks as yours — the file says which is which. */
  it('writes the calls and leaves the load itself to be decided', async () => {
    const { script } = await load();

    expect(script).toContain('Generated by `fougere load`');
    expect(script).toContain('commande.servable');
    expect(script).toContain('const BUDGET = { base: 300, perHop: 200 };');
  }, 30_000);
});
